name: Auto Merge Develop to Staging

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v3
        with:
          ref: 'staging'
          fetch-depth: 0

      - name: Set up git authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Reset staging to develop
        run: |
          git fetch origin develop
          git reset --hard origin/develop
          git push origin staging --force


